$.ajax({
	type:"get", 
	url:"http://appmanta.com/app/keywordanalytics.html?appid=com.word.wordzenen&country=usa&store=gp&device=1", 
	data:{country:"usa",device:1,sdate:"2017-11-06",edate:"2017-11-05",appid:"com.word.wordzenen",uid:"AAAA",page:1,sort:"asc",col:"pos",pagesize:100,timezone:-480,isGoogle:"yes"},
	dataType:"jsonp", 
	jsonpCallback:"datas",
	success:function(data){  
		datas(data); 
	},
});