<?php return array(
'site_title' => '西南传媒大学影视学院活动中心yyy',
'site_keyword' => 'site_keyword',
'site_description'=> 'site_description',
'url' => 'http://127.0.0.1/meiupic/',
'open_pre_resize' => false,
'resize_img_width' => '1600',
'resize_img_height' => '1200',
'resize_quality' => '100',
'demand_resize' => false,
'imgdir_type' => '2',
'size_allow' => '1024000',
'pageset' => '15',
'open_photo' => true,
'gallery_limit' => '60',
'access_ctl' => false,
'access_domain' => '127.0.0.1',
'open_watermark' => true,
'watermark_path' => 'Public/images/logo.png',
'watermark_pos' => 0,
);
